chore: Some minor updates to things
Disabling dns-blocklists package as its not used anymore and just had too many
updates daily.

Using nixfmt-rfc-style for nix file formatting overall.

Trying to figure out a better console kernel param situation.

Updated chrony config to use rtcsync so that grafana shows time as in sync. Not
sure I truly care that much though.

The rest is all not that interesting and rather obvious or commented for future
me to figure out the rationale.

diff --git a/static/home/profile b/static/home/profile
--- a/static/home/profile
+++ b/static/home/profile
@@ -306,8 +306,30 @@ j() {
   fi
 }
 
-# simple wrapper for deploy
+# Stupid simple wrapper function for deploy/darwin-rebuild for macos rebuilds
+# (local only for the latter not tried deploy-rs with darwin nix)
+# TODO: figure out a way to default to the local node hostname to deploy by
+# parsing out the flakes attributes and iff there is a
+# (darwin,nixos)Configuration that matches use that by default otherwise fail
+# and tell the user they have to specify the hostname to deploy/rebuild.
+
 d() {
   host="${1?need a host name}"
-  deploy -ds -- ".#${host}" -L --show-trace
+  # darwin-rebuild need to run as root now
+
+  onmac sudo darwin-rebuild switch --flake ".#${host}" --show-trace
+  onlinux deploy -ds -- ".#${host}" -L --show-trace
+}
+
+NOM="${NOM:-$(command -v nom || echo nom)}"
+
+NOM=$HOME/.nix-profile/bin/nom
+
+nom() {
+  if [ $# -ge 2 ] && [ "$1" = "flake" ] && [ "$2" = "check" ]; then
+    shift 2
+    nix flake check --log-format internal-json -v "$@" 2>&1 | ${NOM} --json
+  else
+    ${NOM} "$@"
+  fi
 }
