static/home/profile: Add an Until Success function
Cause for some reason darwin-rebuild seems to have issues symlinking at times.

diff --git a/static/home/profile b/static/home/profile
--- a/static/home/profile
+++ b/static/home/profile
@@ -473,3 +473,12 @@ ugde() {
     done
   )
 }
+
+# Because stuff sometimes fails, retry Until Success
+us() {
+  ok=1
+  until $ok; do
+    "$@"
+    ok=$?
+  done
+}
